import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await expect(page.getByRole('textbox', { name: 'Username' })).toHaveValue('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();
  await page.locator('svg').first().click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('Johna Doe Doe');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('navigation', { name: 'Sidepanel' }).getByRole('button').click();
  await page.getByRole('link', { name: 'client brand logo' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index');
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('amit');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('');
  await page.getByRole('textbox').nth(1).press('Enter');
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('amit');
  await page.getByRole('button', { name: 'Search' }).click();
  await expect(page.locator('form')).toContainText('Invalid');
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('testname');
  await page.getByText('-- Select --').click();
  await page.getByText('-- Select --').first().click();
  await page.locator('div').filter({ hasText: /^-- Select --$/ }).nth(2).click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('Johna Doe Doe');
  await page.getByText('Johna Doe Doe').click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('123');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('123');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('123456');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('1234567');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('1234567');
  await page.locator('div').filter({ hasText: /^Confirm Password$/ }).first().click();
  await page.getByText('User RoleAdminEmployee NameStatusEnabledUsernameVery Weak PasswordYour password').click();
  await page.getByRole('banner').locator('div').filter({ hasText: /^Admin$/ }).click();
  await expect(page.locator('form')).toContainText('Your password must contain minimum 1 lower-case letter');
});